TYPO3:
  Neos:
    userInterface:
      translation:
        autoInclude:
          'Dotpulse.ResponsiveTabs': ['NodeTypes/*']
    typoScript:
      autoInclude:
        'Dotpulse.ResponsiveTabs': TRUE

Dotpulse:
  ResponsiveTabs:
    includeCss: FALSE
    includeJavascript: FALSE
