Neos:
  Neos:
    userInterface:
      translation:
        autoInclude:
          'Dotpulse.ResponsiveTabs': ['NodeTypes/*']
    fusion:
      autoInclude:
        'Dotpulse.ResponsiveTabs': true

Dotpulse:
  ResponsiveTabs:
    includeCss: false
    includeJavascript: false
